//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materia()
        {
            this.ImagenMaterias = new HashSet<ImagenMateria>();
        }
    
        public int IdMateria { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Creditos { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<byte> IdSemestre { get; set; }
    
        public virtual Semestre Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenMateria> ImagenMaterias { get; set; }
    }
}
